-- Add P2P columns to Nvr
ALTER TABLE "Nvr" ADD COLUMN IF NOT EXISTS "connectionMode" TEXT NOT NULL DEFAULT 'ip';
ALTER TABLE "Nvr" ADD COLUMN IF NOT EXISTS "p2pSerial" TEXT;
ALTER TABLE "Nvr" ALTER COLUMN "ip" DROP NOT NULL;
